sudo: false
addons:
  apt:
    packages:
    - lua5.2
language: cpp
before_install:
  pip install --user sphinx
script:
- python travis/pr-check-base.py
- python travis/lint.py
#- python travis/script-in-readme.py
- python travis/script-syntax.py --ext=lua --cmd="luac5.2 -p"
- python travis/script-syntax.py --ext=rb --cmd="ruby -c"
notifications:
  email: false
