name: Buildmaster rebuild

on:
  workflow_dispatch:
    inputs:
      pull_request:
        description: Pull request ID
        type: string
        required: true  # remove if we support commit rebuilds later

jobs:
  rebuild:
    runs-on: ubuntu-latest
    name: Trigger Buildmaster
    steps:
    - name: Set up Python 3
      uses: actions/setup-python@v4
      with:
        python-version: 3
    - name: Install dependencies
      run: |
        pip install requests
    - name: Clone DFHack
      uses: actions/checkout@v1
      with:
        fetch-depth: 1
        submodules: false
    - name: Run
      env:
        DFHACK_BUILDMASTER_WEBHOOK_URL: ${{ secrets.DFHACK_BUILDMASTER_WEBHOOK_URL }}
        DFHACK_BUILDMASTER_WEBHOOK_SECRET: ${{ secrets.DFHACK_BUILDMASTER_WEBHOOK_SECRET }}
        GITHUB_REPO: ${{ github.repository }}
        GITHUB_TOKEN: ${{ github.token }}
      run: |
        python ci/buildmaster-rebuild-pr.py --pull-request ${{ github.event.inputs.pull_request }}
